name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Create firebase_options.dart if missing
        run: |
          if [ ! -f lib/firebase_options.dart ]; then
            cat << 'EOF' > lib/firebase_options.dart
          // File generated for CI build
          // ignore_for_file: type=lint
          import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
          import 'package:flutter/foundation.dart'
              show defaultTargetPlatform, kIsWeb, TargetPlatform;

          class DefaultFirebaseOptions {
            static FirebaseOptions get currentPlatform {
              if (kIsWeb) {
                return web;
              }
              switch (defaultTargetPlatform) {
                case TargetPlatform.android:
                  return android;
                default:
                  throw UnsupportedError(
                    'DefaultFirebaseOptions are not supported for this platform.',
                  );
              }
            }

            static const FirebaseOptions web = FirebaseOptions(
              apiKey: '${{ secrets.FIREBASE_API_KEY }}',
              appId: '${{ secrets.FIREBASE_APP_ID }}',
              messagingSenderId: '1061338666190',
              projectId: 'my-workbench-app',
              authDomain: 'my-workbench-app.firebaseapp.com',
              storageBucket: 'my-workbench-app.firebasestorage.app',
            );

            static const FirebaseOptions android = FirebaseOptions(
              apiKey: 'AIzaSyDmWlUt3xOhTnWVbGSHYTRWxMnNw_DdkBc',
              appId: '1:1061338666190:android:01eabdc742816ef6462c9f',
              messagingSenderId: '1061338666190',
              projectId: 'my-workbench-app',
              storageBucket: 'my-workbench-app.firebasestorage.app',
            );
          }
          EOF
            sed -i "s/apiKey: ''/apiKey: 'AIzaSyBSlQHX-b_HV2PuH_fKq5QmNoGGMUbJhJ0'/g" lib/firebase_options.dart
            sed -i "s/appId: ''/appId: '1:1061338666190:web:ea7be1fd8f3b0cab462c9f'/g" lib/firebase_options.dart
          fi

      - name: Build Web
        run: flutter build web --release --base-href /workspace/ --no-wasm-dry-run --no-tree-shake-icons

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
